# This file establishes the necessary resources on Azure to deploy a BIG-IP VE
# validated  eduardoc/ansible-azure-labs:azure
#
- name: Deploy BIG-IP 1-NIC on Azure
  hosts: localhost
  vars_files:
    - ./config.yml

  tasks:
    - name: Deploy F5 BIG-IP on Azure - Existing Stack
      azure_rm_deployment:
        state: present
        tenant: "{{ TENANT_ID }}"
        client_id: "{{ CLIENT_ID }}"
        secret: "{{ SERVICE_PRINCIPAL_SECRET }}"
        subscription_id: "{{ SUBSCRIPTION_ID }}"
        resource_group_name: "{{ RESOURCE_GROUP }}"
        location: "{{ DEFAULT_LOCATION }}"
        template_link: "https://raw.githubusercontent.com/F5Networks/f5-azure-arm-templates/master/supported/standalone/1nic/existing-stack/byol/azuredeploy.json"
        parameters:
          authenticationType:
            value: password
          adminUsername:
            value: "{{ ADMINUSERNAME }}"
          adminPasswordOrKey:
            value: "{{ ADMINPASSWORD }}"
          dnsLabel:
            value: "{{ BIGIP_NAME }}-{{ STUDENT_ID }}"
          instanceName:
            value: "{{ BIGIP_NAME }}{{ STUDENT_ID }}"
          instanceType:
            value: "Standard_DS4_v2"
          imageName:
            value: "AllTwoBootLocations"
          bigIpVersion:
            value: "latest"
          licenseKey1:
            value: "{{ BIGIP_LICENSE }}"
          bigIpModules:
            value : "ltm:nominal,asm:nominal,apm:nominal"
          vnetName:
            value: "{{ VNET1 }}"
          vnetResourceGroupName: 
            value: "{{ RESOURCE_GROUP }}"
          mgmtSubnetName:
            value: "{{ VNET_SUBNET1 }}"
          mgmtIpAddress:
            value: "{{ BIGIP_ADDRESS }}"
          avSetChoice:
            value: "CREATE_NEW"     
          provisionPublicIP:
            value: "Yes"
          restrictedSrcAddress:
            value: "{{ ALLOWED_SRC_ADDRESS }}"
          declarationUrl:
            value: "NOT_SPECIFIED"
          ntpServer:
            value: "0.pool.ntp.org"
          timeZone:
            value: UTC
          allowUsageAnalytics:
            value: "Yes"
          zoneChoice:
            value: "1"
          customImage:
            value: "OPTIONAL"
          tagValues: 
            value: {"application":"APP","cost":"COST","environment":"ENV","group":"GROUP","owner":"OWNER"}


