---
# Playbook: license.yaml
# validated  eduardoc/f5-ansible-container:latest
- name: License BIGIP
  connection: local
  hosts: azure-resource-group
  vars_files:
    - ./config.yml
  vars:
    provider:
      server: "{{ ansible_host }}"
      user: "{{ ADMINUSERNAME }}"
      password: "{{ ADMINPASSWORD }}"
      server_port: 8443
      validate_certs: "false"

  tasks:
      - name: Remove the license from the system
        bigip_device_license:
          provider: "{{ provider }}"
          state: "absent"
